# Automatically generated file listings
#
# Creation time: Sun Mar 28 23:19:42 BST 2021

allsrc = src/db/btree.c \
src/db/gdbm.c \
src/db/list.c \
src/db/main.c \
src/db/mysql.c \
src/db/obtree.c \
src/db/sqlite.c \
src/main/help.c \
src/main/log.c \
src/main/main.c \
src/main/options.c \
src/main/tick.c \
src/main/version.c \
src/message/alloc.c \
src/message/base64.c \
src/message/dump.c \
src/message/header.c \
src/message/qp.c \
src/message/read.c \
src/message/rfc2047.c \
src/message/parse.c \
src/spam/alloc.c \
src/spam/allowlist.c \
src/spam/benchmark.c \
src/spam/check.c \
src/spam/cksum.c \
src/spam/db.c \
src/spam/dump.c \
src/spam/merge.c \
src/spam/plaintext.c \
src/spam/token.c \
src/spam/train.c \
src/spam/update.c \
src/spam/prune.c \
src/tests/attached_files.c \
src/tests/gibberish.c \
src/tests/gtube.c \
src/tests/html.c \
src/tests/imgcount.c \
src/tests/main.c \
src/tests/urls.c \
src/library.c \
src/mailbox.c \
src/md5.c

allobj = src/db/btree.o \
src/db/gdbm.o \
src/db/list.o \
src/db/main.o \
src/db/mysql.o \
src/db/obtree.o \
src/db/sqlite.o \
src/main/help.o \
src/main/log.o \
src/main/main.o \
src/main/options.o \
src/main/tick.o \
src/main/version.o \
src/message/alloc.o \
src/message/base64.o \
src/message/dump.o \
src/message/header.o \
src/message/qp.o \
src/message/read.o \
src/message/rfc2047.o \
src/message/parse.o \
src/spam/alloc.o \
src/spam/allowlist.o \
src/spam/benchmark.o \
src/spam/check.o \
src/spam/cksum.o \
src/spam/db.o \
src/spam/dump.o \
src/spam/merge.o \
src/spam/plaintext.o \
src/spam/token.o \
src/spam/train.o \
src/spam/update.o \
src/spam/prune.o \
src/tests/attached_files.o \
src/tests/gibberish.o \
src/tests/gtube.o \
src/tests/html.o \
src/tests/imgcount.o \
src/tests/main.o \
src/tests/urls.o \
src/library.o \
src/mailbox.o \
src/md5.o \
src/.svn.o \
src/.svn/text-base.o \
src/.svn/tmp.o \
src/db.o \
src/db/.svn.o \
src/db/.svn/text-base.o \
src/db/.svn/tmp.o \
src/main.o \
src/main/.svn.o \
src/main/.svn/text-base.o \
src/main/.svn/tmp.o \
src/message.o \
src/message/.svn.o \
src/message/.svn/text-base.o \
src/message/.svn/tmp.o \
src/spam.o \
src/spam/.svn.o \
src/spam/.svn/text-base.o \
src/spam/.svn/tmp.o \
src/tests.o \
src/tests/.svn.o \
src/tests/.svn/text-base.o \
src/tests/.svn/tmp.o

alldep = src/db/btree.d \
src/db/gdbm.d \
src/db/list.d \
src/db/main.d \
src/db/mysql.d \
src/db/obtree.d \
src/db/sqlite.d \
src/main/help.d \
src/main/log.d \
src/main/main.d \
src/main/options.d \
src/main/tick.d \
src/main/version.d \
src/message/alloc.d \
src/message/base64.d \
src/message/dump.d \
src/message/header.d \
src/message/qp.d \
src/message/read.d \
src/message/rfc2047.d \
src/message/parse.d \
src/spam/alloc.d \
src/spam/allowlist.d \
src/spam/benchmark.d \
src/spam/check.d \
src/spam/cksum.d \
src/spam/db.d \
src/spam/dump.d \
src/spam/merge.d \
src/spam/plaintext.d \
src/spam/token.d \
src/spam/train.d \
src/spam/update.d \
src/spam/prune.d \
src/tests/attached_files.d \
src/tests/gibberish.d \
src/tests/gtube.d \
src/tests/html.d \
src/tests/imgcount.d \
src/tests/main.d \
src/tests/urls.d \
src/library.d \
src/mailbox.d \
src/md5.d

